### ISSUE TITLE
Remarques sur le contenu

### ISSUE THREAD

**Issue by Leobouloc** [eig-2017/eig-2017.github.io#3]
j'avais quelques remarques concernant la rubrique "premiers résultats":

> croisement de 2 bases de données internes

j'imagine que vous détaillerez oralement mais c'est un peu abstrait...

> quelques millions économisés

Il s'agit d'économies potentielles pour l'instant...

> Ouverture et partage d'une base de données; un même irritant résolu dans toute l'administration

pareil, ça me semble un peu abstrait...

Par ailleurs, je trouve important de parler dans le rapport d'étonnement ou dans les recommandations de logiciel propriétaire vs. logiciel libre/open source (qui va un peu plus loin que "environnement fermé" je pense)

PS: c'est très élégant votre site je trouve :slightly_smiling_face:

**Comment by seiteta** [comment]
Merci @Leobouloc pour tes remarques ! J'ai mis à jour pour parler d'économies potentielles.
Le reste on détaillera à l'oral.
